### PR TITLE
Added dark version for sketched

### PR DESCRIPTION
**Pull request by Anard**
Light sketched theme is very.... white.
Also os_cap icon added for this version of theme.

### CODE REVIEW

**Comment by vectorsigma72** [comment]
Added

**Comment by vectorsigma72** [comment]
Hi Anard, I realized only now that you forgot to add "screenshot.png". The image must be 743x418 pixels. Please reopen a new PR otherwise I'll remove the theme as the purpose is to have a preview in the theme manager. Thanks in advance

**Comment by vectorsigma72** [comment]
I've added it.

**Comment by Anard** [comment]
Thank you, but I just notice that theme still have some problems :
- cursor moves but click doesn't work
- viewing your screenshot, I'm not sure os_cap, os_yos etc are seen, I always see os_mac icon (but I have only Mojave installed on my computer).

If you have ideas of how to repair, I'm interested...

**Comment by Anard** [comment]
I've uploaded a screenshot with macOS, recovery, Linux and Windows entries here : https://github.com/Anard/CloverThemes

**Comment by vectorsigma72** [comment]
> Thank you, but I just notice that theme still have some problems :
> 
> * cursor moves but click doesn't work
> * viewing your screenshot, I'm not sure os_cap, os_yos etc are seen, I always see os_mac icon (but I have only Mojave installed on my computer).
> 
> If you have ideas of how to repair, I'm interested...

Hi, for the cursors maybe a problem with your bios or your mouse, both are frequent issues with respective manufaturers. About icons... I don't even mind of them. Later I'll try with latest Clover to see...

**Comment by vectorsigma72** [comment]
> I've uploaded a screenshot with macOS, recovery, Linux and Windows entries here : https://github.com/Anard/CloverThemes

Can you kindly make a PR? thanks in advance.

**Comment by Anard** [comment]
About mouse, what I feel strange is it worked before last Clover updates with same hardware (5105 ?, I don't remember exactly).

**Comment by Anard** [comment]
It's OK for Mojave icon : it's os_moja.icns instead of os_moj.icns (since a long time I think …)
I'll try other themes to see if my mouse clic can work.

**Comment by Anard** [comment]
Hi back
Just too say : r5108 fixes my mouse issue !

**Pull request merged**
